valkey:
  host: valkey
  port: 6379
mqtt:
  host: "mqtt.auroraborealis.cloud"
  listeners:
    tcp: 1883
    ssl: 8883
    ws: 8083
    wss: 8084
minio:
  endpoint: "s3.auroraborealis.cloud"
  secure: true